<a href="https://colab.research.google.com/github/Monica-456/Data-Analysis/blob/main/Yet_another_copy_of_DA_practice_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
number = int(input("enter a number:"))
if number%2==0:
  print("given number is a prime")
else:
  print("given number is not a prime")

enter a number:5
given number is not a prime

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
print("pandas imported")

pandas imported

In [ ]:
#creating a series
data = [1,2,3,4]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#creating user-defined index
data=[1,2,3,4,5]
i=['a','b','e','c','d']
s = pd.Series(data, index=i)
print (s)

a    1
b    2
e    3
c    4
d    5
dtype: int64

In [ ]:
#creating series with dictionary
s2 = pd.Series({'x':100,'y':200,'z':300})
print(s2)

x    100
y    200
z    300
dtype: int64

In [ ]:
#accessing elements
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])

100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64

/tmp/ipykernel_1657/3002422712.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])

In [ ]:
#particular position
print(s2[2])

300

/tmp/ipykernel_1657/2067221450.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[2])

In [ ]:
#inserting new data(directly,concate)
s['f'] = 80
print(s)

a     1
b     2
e     3
c     4
d     5
f    80
dtype: int64

In [ ]:
#remove(drop,methood)
s=s.drop('a')
print (s)

b     2
e     3
c     4
d     5
f    80
dtype: int64

In [ ]:
#updating
s['a'] = 10
print(s)

b     2
e     3
c     4
d     5
f    80
a    10
dtype: int64

In [ ]:
#creating a pandas series
marks = [78,85,92,67,88]
i= ['101','102','103','104','105']
s=pd.Series(marks,index=i)
print(s)
#display the marks of 103
print(s['103'])
#change the marks of 104 from 67 to 75
s['104']=75
print(s)
#delete 102
s=s.drop('102')
print(s)
#add 106 as 96
s['106']=96
print(s)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    96
dtype: int64

In [ ]:
#employee id :1001,1002,1003,1004,1005
#salary : 35000,42000,38000,50000,45000

#create a series
import pandas as pd
salary =[35000,42000,38000,50000,45000]
id = [1001,1002,1003,1004,1005]
e = pd.Series(salary,index=id)
print(e)
#increase the salary of employees 1003 to 40000
e[1004]=40000
print(e)
#delete employee 1002
e=e.drop(1002)
print(e)
#add employee 1006 with salary 55000
e[1006]=55000
print(e)
#display the first 3 employees
print(e[:3])

1001    35000
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64
1001    35000
1002    42000
1003    38000
1004    40000
1005    45000
dtype: int64
1001    35000
1003    38000
1004    40000
1005    45000
dtype: int64
1001    35000
1003    38000
1004    40000
1005    45000
1006    55000
dtype: int64
1001    35000
1003    38000
1004    40000
dtype: int64

In [ ]:
#product prices
#product id : p101,p102,p103,p104,p105
#price 500,750,1200,900,1500

#create series
import pandas as pd
price =[500,750,1200,900,1500]
id = ['P101','P102','P103','P104','P105']
p=pd.Series(price,index=id)
print(p)
#Dispaly the price of p103
print(p['P103'])
#change the price of P102 TO 800
p['P102']=800
print(p)
#delete P104
p=p.drop('P102')
print(p)
#add a new product P106 with price 2000
p['P106']=2000
print(p)

P101     500
P102     750
P103    1200
P104     900
P105    1500
dtype: int64
1200
P101     500
P102     800
P103    1200
P104     900
P105    1500
dtype: int64
P101     500
P103    1200
P104     900
P105    1500
dtype: int64
P101     500
P103    1200
P104     900
P105    1500
P106    2000
dtype: int64

In [ ]:
#weather application
#monday,tuesday,wednesday,thursday,friday saturday,sunday
#31,32,34,33,35,36,34

#create pandas series
import pandas as pd
date=[31,32,34,33,35,36,34]
day=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
d=pd.Series(date,index=day)
print(d)
#display the temperature from monday to wednesday
print(d[:3])
#chnage thursday temperature to 32
d['thursday']=32
print(d)
#delete saturdays temperature
d=d.drop('saturday')
print(d)
#add monday of the enxt week with temperature 30
d['Monday of next week']=30
print(d)

monday       31
tuesday      32
wednesday    34
thursday     33
friday       35
saturday     36
sunday       34
dtype: int64
monday       31
tuesday      32
wednesday    34
dtype: int64
monday       31
tuesday      32
wednesday    34
thursday     32
friday       35
saturday     36
sunday       34
dtype: int64
monday       31
tuesday      32
wednesday    34
thursday     32
friday       35
sunday       34
dtype: int64
monday                 31
tuesday                32
wednesday              34
thursday               32
friday                 35
sunday                 34
Monday of next week    30
dtype: int64

In [ ]:
#creating a series with customs index
import pandas as pd
s=pd.Series(
    [5000,7000,6000,9000,8000],
            index=['Monday','Tuesday','Wednesday','Thursday','Friday'])
print(s)

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
Friday       8000
dtype: int64

5

In [ ]:
#head():- prints first 5 elements by default
s.head()

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
Friday       8000
dtype: int64

In [ ]:
#tail():-prints last 5 elements by default
s.tail()

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
Friday       8000
dtype: int64

In [ ]:
#len(s) gives the length if s
len(s)

5

In [ ]:
#gives the shape
s.shape

(5,)

In [ ]:
#index:-gives the index
s.index

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], dtype='object')

In [ ]:
#filtering
#selecting using single index
s["Monday"]

np.int64(5000)

In [ ]:
#selecting using multiple index(list inside list)
s[["Monday","Wednesday"]]

Monday       5000
Wednesday    6000
dtype: int64

In [ ]:
#filtering using a condidtion(since its  a condition use print)(output is boolean)
print(s>6000)

Monday       False
Tuesday       True
Wednesday    False
Thursday      True
Friday        True
dtype: bool

In [ ]:
#to get a VALUE rather than boolean Give the condition inside a list
print(s[s>6000])

Tuesday     7000
Thursday    9000
Friday      8000
dtype: int64

In [ ]:
#CLEANNING DATA
#missing values:- ibn seies missing values are represented by NaN

import pandas as pd
s=pd.Series([5000,7000,None,9000,None])
print(s)

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
#resulting the missing values(isna() identifies the missing values and returns boolean values)
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
#to count the missing values use Sum()
s.isna().sum()

np.int64(2)

In [ ]:
#fillna() method used to replace or fill the missing values, have to pass the required number or string anything is allowed
s.fillna(0)

0    5000.0
1    7000.0
2       0.0
3    9000.0
4       0.0
dtype: float64

In [ ]:
import pandas as pd
s=pd.Series([5000,7000,None,9000,None])
print(s)

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
#dropna() method is used to drop the missing values
s.dropna()

0    5000.0
1    7000.0
3    9000.0
dtype: float64

In [ ]:
#replacing the values (diff btw s.drop and s=s.drop is thet s= is permenant whilte the other is runtime change)
s=s.replace(5000,5500)
print(s)

0    5500.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
#creating a DataFrame

import pandas as pd
data = [["Ravi","22","30000"],
        ["Prinya","24","40000"],
        ["Arun","21","28000"]]
df=pd.DataFrame(data)
print(df)

        0   1      2
0    Ravi  22  30000
1  Prinya  24  40000
2    Arun  21  28000

In [ ]:
#creating dataframe using tuple
import pandas as pd
data = (("Satya","22","70000"),
        ("Monica","21","80000"),
        ("Arun","22","90000"))
df=pd.DataFrame(data)
print(df)

        0   1      2
0   Satya  22  70000
1  Monica  21  80000
2    Arun  22  90000

In [ ]:
#creating DataFrame using a set
import pandas as pd
data = {100,200,300,400}
df = pd.DataFrame(list(data))
print(df)

     0
0  200
1  100
2  400
3  300

In [ ]:
#creating a dataFrame using a dictionary
#dictionary key = column name(should be unique)
#dictionary values = row name
data = {'Name': ["alice","Bob","charlie"],
        'Age': [21,22,33],
        'City':["NY","Germany","LA"]}
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    alice   21       NY
1      Bob   22  Germany
2  charlie   33       LA

In [ ]:
#converting a series to DataFrame
s=pd.Series([1,2,3,4],
            name='Numbers')
df = s.to_frame()
print(df)

   Numbers
0        1
1        2
2        3
3        4

In [ ]:
#converting multiple series into one DataFrame
s1=pd.Series([1,2,3,4],name='Numbers')
s2 = pd.Series([5,6,7,8],name='integers')
s3 = pd.Series([9,2,3,4],name='nums')
df = s1,s2,s3.to_frame()
print(df)

(0    1
1    2
2    3
3    4
Name: Numbers, dtype: int64, 0    5
1    6
2    7
3    8
Name: integers, dtype: int64,    nums
0     9
1     2
2     3
3     4)

In [ ]:
#create a table of 5 strudents with 3 subjects
import pandas as pd
data={'Maths':[90,91,91,89,79],
      'Physics':[93,94,95,67,87],
      'Chemistry':[96,97,98,88,99]}
students=("Alice","Bob","Charlie","Divya","Eveya")
df=pd.DataFrame(data,index=students)
print(df)

         Maths  Physics  Chemistry
Alice       90       93         96
Bob         91       94         97
Charlie     91       95         98
Divya       89       67         88
Eveya       79       87         99

In [ ]:
#create a DataFrame sales and profit and loss using a tuple
import pandas as pd
data = [("Monday", 1200, 200),
        ("Tuesday", 900, -50),
        ("Wednesday", 1500, 400),
        ("Thursday", 800, -120),
        ("Friday", 2000, 650),
        ("Saturday", 2500, 900),
        ("Sunday", 1700, 300)]
df = pd.DataFrame(data, columns=["Day", "Sales", "Profit_Loss"])
print(df)

         Day  Sales  Profit_Loss
0     Monday   1200          200
1    Tuesday    900          -50
2  Wednesday   1500          400
3   Thursday    800         -120
4     Friday   2000          650
5   Saturday   2500          900
6     Sunday   1700          300

In [ ]:
#create a dataFrame using a dictionary
import pandas as pd
data={'Name':["parimala","jahnavi","Lavanya","lohitha","Meghana"],
      'Total_days':[30,30,30,30,30],
      'Days_present':[28,29,27,26,25],
      'Days_absent':[2,1,3,4,5]}
pf=pd.DataFrame(data)
print(pf)

       Name  Total_days  Days_present  Days_absent
0  parimala          30            28            2
1   jahnavi          30            29            1
2   Lavanya          30            27            3
3   lohitha          30            26            4
4   Meghana          30            25            5

In [ ]:
#loc and iloc functions, iloc is for integers while loc we have to specify during indexing
import pandas as pd
s=pd.Series(
    [5000,7000,6000,9000,8000],
    index=["Monday","Tuesday","Wednesday","Thursday","Friday"]
)
print(s)
s.iloc[0]
s.iloc[0:3]
s.loc["Monday"]

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
Friday       8000
dtype: int64

np.int64(5000)

In [ ]:
import pandas as pd

data={
    "Name":["ravi","priya","Arun","Sneha","Kiran","Anjali","vikram","Meena"],
    "Age":[22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None,"bangalore","mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,None,55000]

}
i=[101,102,103,104,105,106,107,108]

df =pd.DataFrame(data,index=i)
print(df)
df.iloc[0:3]
df.loc[101]
df.loc[101:103] #unlike iloc it displays all values from 101 102 103

       Name   Age       City   Salary
101    ravi  22.0  Hyderabad  30000.0
102   priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  vikram  20.0  bangalore      NaN
108   Meena  27.0     mumbai  55000.0

      Name   Age       City   Salary
101   ravi  22.0  Hyderabad  30000.0
102  priya  24.0    Chennai  40000.0
103   Arun   NaN  Bangalore  28000.0

In [ ]:
#aggregation functions :-sum,mean,min,max,count,median,std for standard deviation
import pandas as pd
s=pd.Series(
    [5000,7000,6000,9000,8000],
    index=["Monday","Tuesday","Wednesday","Thursday","Friday"]
)
print(s)
s.min()
s.max()
s.count()
s.mean()
s.median()
s.std()
s.sum()

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
Friday       8000
dtype: int64

np.int64(35000)

In [ ]:
import pandas as pd

data={
    "Name":["ravi","priya","Arun","Sneha","Kiran","Anjali","vikram","Meena"],
    "Age":[22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None,"bangalore","mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,None,55000]

}
i=[101,102,103,104,105,106,107,108]
df =pd.DataFrame(data,index=i)
print(df)

       Name   Age       City   Salary
101    ravi  22.0  Hyderabad  30000.0
102   priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  vikram  20.0  bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
#concatination on series
#combining of two series
#ignore_index=True == to get unique index number
import pandas as pd
s1 = pd.Series([101,102,103])
s2 = pd.Series([104,105,106])
c=pd.concat([s1,s1],ignore_index=True)
print(c)

0    101
1    102
2    103
3    101
4    102
5    103
dtype: int64

In [ ]:
#E-Commerce sales
#create the series with dtaes as indexes
import pandas as pd
data=(25000,28000,32000,None,35000,38000,None,42000,45000,48000)
i=["aug-1","aug-2","aug-3","aug-4","aug-5","aug-6","aug-7","aug-8","aug-9","aug-10"]
sale=pd.Series(data,index=i)
print(sale)

aug-1     25000.0
aug-2     28000.0
aug-3     32000.0
aug-4         NaN
aug-5     35000.0
aug-6     38000.0
aug-7         NaN
aug-8     42000.0
aug-9     45000.0
aug-10    48000.0
dtype: float64

In [ ]:
#display the first 3 days
sale.head()

aug-1    25000.0
aug-2    28000.0
aug-3    32000.0
aug-4        NaN
aug-5    35000.0
dtype: float64

In [ ]:
#display last 3 days
sale.tail(3)

aug-8     42000.0
aug-9     45000.0
aug-10    48000.0
dtype: float64

In [ ]:
#find all missing values
sale.isna()

aug-1     False
aug-2     False
aug-3     False
aug-4      True
aug-5     False
aug-6     False
aug-7      True
aug-8     False
aug-9     False
aug-10    False
dtype: bool

In [ ]:
#count the missing values
sale.isna().sum()

np.int64(2)

In [ ]:
#replace the null values with the average sales
sale=sale.fillna(sale.mean())
print(sale)

aug-1     25000.0
aug-2     28000.0
aug-3     32000.0
aug-4     36625.0
aug-5     35000.0
aug-6     38000.0
aug-7     36625.0
aug-8     42000.0
aug-9     45000.0
aug-10    48000.0
dtype: float64

In [ ]:
#display sales greater than than 35000
sale>35000

aug-1     False
aug-2     False
aug-3     False
aug-4      True
aug-5     False
aug-6      True
aug-7      True
aug-8      True
aug-9      True
aug-10     True
dtype: bool

In [ ]:
#change the sales of aug 3 to 34000
sale["aug-3"]=34000
print(sale)

aug-1     25000.0
aug-2     28000.0
aug-3     34000.0
aug-4     36625.0
aug-5     35000.0
aug-6     38000.0
aug-7     36625.0
aug-8     42000.0
aug-9     45000.0
aug-10    48000.0
dtype: float64

In [ ]:
#delete the sales data for aug 04
sale=sale.drop("aug-4")
print(sale)

aug-1     25000.0
aug-2     28000.0
aug-3     32000.0
aug-5     35000.0
aug-6     38000.0
aug-7         NaN
aug-8     42000.0
aug-9     45000.0
aug-10    48000.0
dtype: float64

In [ ]:
#add sales for 11 aug as 50000
sale["aug-11"] = 50000
print(sale)

aug-1     25000.0
aug-2     28000.0
aug-3     32000.0
aug-5     35000.0
aug-6     38000.0
aug-7         NaN
aug-8     42000.0
aug-9     45000.0
aug-10    48000.0
aug-11    50000.0
dtype: float64

In [ ]:
#find total sales
s=sale.sum()
print(s)

343000.0

In [ ]:
#find average sales
avg=sale.mean()
print(avg)

38111.11111111111

In [ ]:
#find highest sales
max=sale.max()
print(max)

50000.0

In [ ]:
#find lowest sales
min=sale.min()
print(min)

25000.0

In [ ]:
#month and revenue
import pandas as pd
data=(120000,135000,None,150000,165000,None,180000,195000,210000,225000)
month =('January','February','March','April','May','June','July','August','september','October')
sale=pd.Series(data,index=month)
print(sale)

January      120000.0
February     135000.0
March             NaN
April        150000.0
May          165000.0
June              NaN
July         180000.0
August       195000.0
september    210000.0
October      225000.0
dtype: float64

In [ ]:
#display the first 5 months
sale.head()

January     120000.0
February    135000.0
March            NaN
April       150000.0
May         165000.0
dtype: float64

In [ ]:
#display last 3 months
sale.tail(3)

August       195000.0
september    210000.0
October      225000.0
dtype: float64

In [ ]:
#diaplay january,march,may
sale[["January","March","May"]]

January    120000.0
March           NaN
May        165000.0
dtype: float64

In [ ]:
#display revenue greater thann 170000
sale>170000

January      False
February     False
March        False
April        False
May          False
June         False
July          True
August        True
september     True
October       True
dtype: bool

In [ ]:
#identify missing values
sale.isna()

January      False
February     False
March         True
April        False
May          False
June          True
July         False
August       False
september    False
October      False
dtype: bool

In [ ]:
#count missing values
sale.isna().sum()

np.int64(2)

In [ ]:
#fill the missing vaules using average revenue
sale=sale.fillna(sale.mean())
print(sale)

January      120000.0
February     135000.0
March        172500.0
April        150000.0
May          165000.0
June         172500.0
July         180000.0
August       195000.0
september    210000.0
October      225000.0
dtype: float64

In [ ]:
#change april revenue to 155000
sale["April"]=155000
print(sale)

January      120000.0
February     135000.0
March             NaN
April        155000.0
May          165000.0
June              NaN
July         180000.0
August       195000.0
september    210000.0
October      225000.0
dtype: float64

In [ ]:
#delete february
sale.drop("February")

January      120000.0
March        172500.0
April        155000.0
May          165000.0
June         172500.0
July         180000.0
August       195000.0
september    210000.0
October      225000.0
dtype: float64

In [ ]:
#add reveneue with revenue 240000
sale["November"]=240000
print(sale)

January      120000.0
February     135000.0
March             NaN
April        150000.0
May          165000.0
June              NaN
July         180000.0
August       195000.0
september    210000.0
October      225000.0
November     240000.0
dtype: float64

In [ ]:
#calculate total revenue
total=sale.sum()
print(total)

1620000.0

In [ ]:
from numpy import average
#calcuate average revenue
average=sale.mean()
print(average)

173125.0

In [ ]:
#find maximum
max=sale.max()
print(max)

225000.0

In [ ]:
#find minimum
min=sale.min()
print(min)

120000.0

In [ ]:
#create another series for december and combine it with existing series using pd.concat()
import pandas as pd
s1 = sale
s2 = pd.Series({"December":120000})
cat=pd.concat([s1,s2])
print(cat)

NameError: name 'sale' is not defined

In [ ]:
import pandas as pd

data={
    "Name":["ravi","priya","Arun","Sneha","Kiran","Anjali","vikram","Meena"],
    "Age":[22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None,"bangalore","mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,None,55000]

}
i=[101,102,103,104,105,106,107,108]
df =pd.DataFrame(data,index=i)
print(df)

       Name   Age       City   Salary
101    ravi  22.0  Hyderabad  30000.0
102   priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  vikram  20.0  bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
#remove columns containing missing values
df.dropna(axis=0)

      Name   Age       City   Salary
101   ravi  22.0  Hyderabad  30000.0
102  priya  24.0    Chennai  40000.0
104  Sneha  25.0  Hyderabad  50000.0
108  Meena  27.0     mumbai  55000.0

In [ ]:
df.dropna(axis=1)

       Name
101    ravi
102   priya
103    Arun
104   Sneha
105   Kiran
106  Anjali
107  vikram
108   Meena

In [ ]:
#filling missing values
#1.filling with 0(fillis with 0 for every missing value)
df.fillna(0)

       Name   Age       City   Salary
101    ravi  22.0  Hyderabad  30000.0
102   priya  24.0    Chennai  40000.0
103    Arun   0.0  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   0.0     Mumbai  35000.0
106  Anjali  26.0          0  45000.0
107  vikram  20.0  bangalore      0.0
108   Meena  27.0     mumbai  55000.0

In [ ]:
#filling different columns with differenet values
df.fillna({'Age':12,
           'City':'Vizag'})

       Name   Age       City   Salary
101    ravi  22.0  Hyderabad  30000.0
102   priya  24.0    Chennai  40000.0
103    Arun  12.0  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran  12.0     Mumbai  35000.0
106  Anjali  26.0      Vizag  45000.0
107  vikram  20.0  bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
#filling numerical misisng values with mean
df['Age']=df['Age'].fillna(df['Age'].mean())
print(df)

       Name   Age       City   Salary
101    ravi  22.0  Hyderabad  30000.0
102   priya  24.0    Chennai  40000.0
103    Arun  24.0  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran  24.0     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  vikram  20.0  bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
import pandas as pd
emp_details={"EmpID":[101,102,103,104,101],
             "City":["Hyderabad","Chennai","Bangalore",None,"Hyderabad"],
             "Experience":[None,4,3,5,2],
             "Age":[25,30,None,35,25]
             }
df=pd.DataFrame(emp_details)
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101  Hyderabad         2.0  25.0

In [ ]:
#perform all the missing operations
df.isna()
df.isna().sum()

EmpID         0
City          1
Experience    1
Age           1
dtype: int64

In [ ]:
#fill missing valuesin city with "unknown"
df.fillna({"City":'Unknown'})

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104    Unknown         5.0  35.0
4    101  Hyderabad         2.0  25.0

In [ ]:
#fill experience with 0
df.fillna(0)

   EmpID       City  Experience   Age
0    101  Hyderabad         0.0  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   0.0
3    104          0         5.0  35.0
4    101  Hyderabad         2.0  25.0

In [ ]:
#Age with median()
df['Age']=df['Age'].fillna(df['Age'].median())
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0  27.5
3    104       None         5.0  35.0
4    101  Hyderabad         2.0  25.0

In [ ]:
#"empid" = "employee_id"
df.rename(columns={"EmpID"=="Employee_id"})

TypeError: 'set' object is not callable

In [ ]:
#create a new column salary for all the employees
df["Salary"] = [20000,30000,4000,50000,60000]
print(df)

   EmpID       City  Experience   Age  Salary
0    101  Hyderabad         NaN  25.0   20000
1    102    Chennai         4.0  30.0   30000
3    104       None         5.0  35.0    4000
4    101  Hyderabad         2.0  25.0   50000
5    109       pune         4.0  25.0   60000

In [ ]:
#age plus 1
df["Age"]=df(["Age"]+1)
print(df)

TypeError: can only concatenate list (not "int") to list

In [ ]:
#create a new column every person got 10%hike on their present salary
df["bonus"] = df["Salary"]*0.10
print(df)

   EmpID       City  Experience   Age  Salary   bonus
0    101  Hyderabad         NaN  25.0   20000  2000.0
1    102    Chennai         4.0  30.0   30000  3000.0
2    103  Bangalore         3.0   NaN    4000   400.0
3    104       None         5.0  35.0   50000  5000.0
4    101  Hyderabad         2.0  25.0   60000  6000.0

In [ ]:
#deleting a column
df.drop('bonus',axis=1,inplace=True)
print(df)

KeyError: "['bonus'] not found in axis"

In [ ]:
#droppping multiple values
df.drop(columns=["Salary"],inplace=True)

In [ ]:
#Neww
import pandas as pd
emp_details={"EmpID":[101,102,103,104,101],
             "City":["Hyderabad","Chennai","Bangalore",None,"Hyderabad"],
             "Experience":[None,4,3,5,2],
             "Age":[25,30,None,35,25]
             }
df=pd.DataFrame(emp_details)
print(df)
df.loc[len(df)]=[109,'pune',4,25]
print(df)
df.drop(2,axis=0,inplace=True)
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101  Hyderabad         2.0  25.0
   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101  Hyderabad         2.0  25.0
5    109       pune         4.0  25.0
   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
3    104       None         5.0  35.0
4    101  Hyderabad         2.0  25.0
5    109       pune         4.0  25.0

In [ ]:
#aggregation functions using group by
df.groupby('City')['Age'].min()
df.groupby('City')['Age'].max()
df.groupby('City')['Age'].sum()
df.groupby('City')['Age'].count()
df.groupby('City')['Age'].mean()

City
Chennai      30.0
Hyderabad    25.0
pune         25.0
Name: Age, dtype: float64

In [2]:
#homework 1
import pandas as pd
data = {
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena"],
    "Age": [22, 24, 21, 25, 23, 26, 20, 27],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
             "Mumbai", "Chennai", "Bangalore", "Mumbai"],
    "Salary": [30000, 40000, 28000, 50000, 35000, 45000, 25000, 55000]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
1   Priya   24    Chennai   40000
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000
6  Vikram   20  Bangalore   25000
7   Meena   27     Mumbai   55000

In [3]:
#2) Show only Name column
print(df["Name"])

0      Ravi
1     Priya
2      Arun
3     Sneha
4     Kiran
5    Anjali
6    Vikram
7     Meena
Name: Name, dtype: object

In [4]:
#3)Show only Name and Salary
print(df[["Name", "Salary"]])

     Name  Salary
0    Ravi   30000
1   Priya   40000
2    Arun   28000
3   Sneha   50000
4   Kiran   35000
5  Anjali   45000
6  Vikram   25000
7   Meena   55000

In [7]:
#4)Employees older than 23
print(df[df["Age"] > 23])

     Name  Age       City  Salary
1   Priya   24    Chennai   40000
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000

In [8]:
#5)Employees earning more than 40000
print(df[df["Salary"] > 40000])

     Name  Age       City  Salary
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000

In [9]:
#6)Employees from Chennai
print(df[df["City"] == "Chennai"])

     Name  Age     City  Salary
1   Priya   24  Chennai   40000
5  Anjali   26  Chennai   45000

In [10]:
#7)Age > 22 and Salary > 35000
print(df[(df["Age"] > 22) & (df["Salary"] > 35000)])

     Name  Age       City  Salary
1   Priya   24    Chennai   40000
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000

In [12]:
#8)City is Mumbai or Bangalore
print(df[(df["City"] == "Mumbai") | (df["City"] == "Bangalore")])

     Name  Age       City  Salary
2    Arun   21  Bangalore   28000
4   Kiran   23     Mumbai   35000
6  Vikram   20  Bangalore   25000
7   Meena   27     Mumbai   55000

In [13]:
#9)Name and Salary where Salary > 30000
print(df[df["Salary"] > 30000][["Name", "Salary"]])

     Name  Salary
1   Priya   40000
3   Sneha   50000
4   Kiran   35000
5  Anjali   45000
7   Meena   55000

In [16]:
#10) 2nd, 3rd, 4th employees
print(df.iloc[1:4])

    Name  Age       City  Salary
1  Priya   24    Chennai   40000
2   Arun   21  Bangalore   28000
3  Sneha   25  Hyderabad   50000

In [17]:
#11) First 4 employees, only Name and Age
print(df.loc[0:3, ["Name", "Age"]])

    Name  Age
0   Ravi   22
1  Priya   24
2   Arun   21
3  Sneha   25

In [18]:
# 12)1st, 4th, 7th employees
print(df.iloc[[0, 3, 6]])

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
3   Sneha   25  Hyderabad   50000
6  Vikram   20  Bangalore   25000

In [19]:
#13)Employees with index 2 to 5
print(df.loc[2:5])

     Name  Age       City  Salary
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000

In [20]:
#14)Rename all columns
rename_= df.rename(columns={"Name": "Employee_Name", "Age": "Employee_Age",
                          "City": "Location", "Salary": "Monthly_Salary"})
print(rename_)

  Employee_Name  Employee_Age   Location  Monthly_Salary
0          Ravi            22  Hyderabad           30000
1         Priya            24    Chennai           40000
2          Arun            21  Bangalore           28000
3         Sneha            25  Hyderabad           50000
4         Kiran            23     Mumbai           35000
5        Anjali            26    Chennai           45000
6        Vikram            20  Bangalore           25000
7         Meena            27     Mumbai           55000

In [65]:
#15)Age between 22 and 26, show Name, City, Salary
print(df[(df["Age"] >= 22) & (df["Age"] <= 26)][["Name", "City", "Salary"]])

KeyError: 'Age'

In [1]:
#DAY-7 (GROUP BY)
import pandas as pd
emp_details = {
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore","Vizag","Hyderbad"],
    "Experience":[3,4,3,5,2],
    "Age":[25,30,22,35,25]
}
df=pd.DataFrame(emp_details)
print(df)

   EmpID       City  Experience  Age
0    101  Hyderabad           3   25
1    102    Chennai           4   30
2    103  Bangalore           3   22
3    104      Vizag           5   35
4    101   Hyderbad           2   25

In [2]:
#Basic Groupby()
df.groupby('City')['Age'].mean()

City
Bangalore    22.0
Chennai      30.0
Hyderabad    25.0
Hyderbad     25.0
Vizag        35.0
Name: Age, dtype: float64

In [3]:
#Groupby on single column with multiple aggregations
df.groupby('City')['Age'].agg(['mean','max','min'])

           mean  max  min
City
Bangalore  22.0   22   22
Chennai    30.0   30   30
Hyderabad  25.0   25   25
Hyderbad   25.0   25   25
Vizag      35.0   35   35

In [4]:
#Groupby On Multiple Columns With Multiple Aggregations
df.groupby('City').agg({
    'Age':['mean','max'],
    'Experience':['sum','count']
})

            Age     Experience
           mean max        sum count
City
Bangalore  22.0  22          3     1
Chennai    30.0  30          4     1
Hyderabad  25.0  25          3     1
Hyderbad   25.0  25          2     1
Vizag      35.0  35          5     1

In [5]:
# Merges and Joins (Left,right,inner,full outer)
df1=pd.DataFrame({
    'ID':[1,2,3],
    'Name':['A','B','c']
})
df2=pd.DataFrame({
    'ID': [1,2,3],
    'Salary':[1000,2000,3000]
})
print(df1)
print(df2)

   ID Name
0   1    A
1   2    B
2   3    c
   ID  Salary
0   1    1000
1   2    2000
2   3    3000

In [6]:
merged=pd.merge(df1,df2,on='ID',how='inner')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [7]:
merged=pd.merge(df1,df2,on='ID',how='outer')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [8]:
merged=pd.merge(df1,df2,on='ID',how='left')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [9]:
merged=pd.merge(df1,df2,on='ID',how='right')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [10]:
combined=pd.concat(
    [df1,df2],
    axis=0,
    ignore_index=True)

In [11]:
combined=pd.concat(
    [df1,df2],
    axis=1,
    ignore_index=True)

In [12]:
#Working on CSV Files
import pandas as pd
df=pd.read_csv('/content/sample_data/california_housing_train.csv')
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]

In [13]:
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0

In [14]:
print(df.tail())

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

In [15]:
print(df.shape)

(17000, 9)

In [16]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB
None

In [17]:
print(df.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000

In [19]:
#today
import pandas as pd
data={
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
    "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
    "Salary":[30000,40000,35000,45000,32000,50000,38000,42000,36000,45000,45000]
}
df=pd.DataFrame(data)
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [21]:
#delete entire rows based on specific column duplicates
df=df.drop_duplicates(subset=["EmpID"],keep="first")
print(df)

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  Hyderabad   40000
2    103    Arun    CHENNAI   35000
3    104   sneha    Chennai   45000
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [24]:
#INCONSISTENCY DATA:- it is done using string methods
df["City"]=df["City"].str.title()
print(df)

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  Hyderabad   40000
2    103    Arun    Chennai   35000
3    104   sneha    Chennai   45000
4    105   Kiran  Bangalore   32000
5    106  ANJALI  Bangalore   50000
6    107  Vikram     Mumbai   38000
7    108   meena     Mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [25]:
df["City"]=df["City"].str.lower()
print(df)

   EmpID    Name       City  Salary
0    101    Ravi  hyderabad   30000
1    102   PRIYA  hyderabad   40000
2    103    Arun    chennai   35000
3    104   sneha    chennai   45000
4    105   Kiran  bangalore   32000
5    106  ANJALI  bangalore   50000
6    107  Vikram     mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      delhi   36000
9    110   Sneha  hyderabad   45000

In [26]:
df["City"]=df["City"].str.upper()
print(df)

   EmpID    Name       City  Salary
0    101    Ravi  HYDERABAD   30000
1    102   PRIYA  HYDERABAD   40000
2    103    Arun    CHENNAI   35000
3    104   sneha    CHENNAI   45000
4    105   Kiran  BANGALORE   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     MUMBAI   38000
7    108   meena     MUMBAI   42000
8    109   RAHUL      DELHI   36000
9    110   Sneha  HYDERABAD   45000

In [64]:
import pandas as pd
data = {
   "TransactionID": [1001, 1002, 1003, 1004, 1005,1006, 1007, 1008, 1009, 1010, 1010, 1011],
   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran","Anjali", "Vikram", "Meena", "Rahul", "Sneha","Sneha", "Kiran"],
   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse","Keyboard", "Monitor", "Laptop", "Mobile", "Headphones", "Headphones", "Mouse"],
   "Amount": [55000, 25000, 30000, 5000, 1500,2500, 18000, 55000, 22000, 5000, 5000, 1500]}
df = pd.DataFrame(data)
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [30]:
#convert all values in the customer column into lowercase
df["Customer"]=df["Customer"].str.lower()
print(df)

    TransactionID Customer     Product  Amount
0            1001     ravi      Laptop   55000
1            1002    priya      Mobile   25000
2            1003     arun      Tablet   30000
3            1004    sneha  Headphones    5000
4            1005    kiran       Mouse    1500
5            1006   anjali    Keyboard    2500
6            1007   vikram     Monitor   18000
7            1008    meena      Laptop   55000
8            1009    rahul      Mobile   22000
9            1010    sneha  Headphones    5000
10           1010    sneha  Headphones    5000
11           1011    kiran       Mouse    1500

In [33]:
#the first letter of each name should be capitalized, standardize the customer columnn
df["Customer"]=df["Customer"].str.capitalize()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [36]:
#remove leading and trailing spaces fron customer column
df["Customer"]=df["Customer"].str.strip()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [38]:
#standardize the product column by converting all product names into lower
df["Product"]=df["Product"].str.lower()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      laptop   55000
1            1002    Priya      mobile   25000
2            1003     Arun      tablet   30000
3            1004    Sneha  headphones    5000
4            1005    Kiran       mouse    1500
5            1006   Anjali    keyboard    2500
6            1007   Vikram     monitor   18000
7            1008    Meena      laptop   55000
8            1009    Rahul      mobile   22000
9            1010    Sneha  headphones    5000
10           1010    Sneha  headphones    5000
11           1011    Kiran       mouse    1500

In [39]:
#convert product name to title case
df["Product"]=df["Product"].str.title()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [50]:
#clean both customer anmd product columns by removing leading/trailing spaces and convert the values into title case
df["Customer"],df["Product"]=df["Customer"].str.strip().str.title(),df["Product"].str.strip().str.title()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [47]:
#standaridize the product values and display the matching transactions regardless  of any pattern as"laptop"
df["Product"]=df["Product"].str.lower()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      laptop   55000
1            1002    Priya      mobile   25000
2            1003     Arun      tablet   30000
3            1004    Sneha  headphones    5000
4            1005    Kiran       mouse    1500
5            1006   Anjali    keyboard    2500
6            1007   Vikram     monitor   18000
7            1008    Meena      laptop   55000
8            1009    Rahul      mobile   22000
9            1010    Sneha  headphones    5000
10           1010    Sneha  headphones    5000
11           1011    Kiran       mouse    1500

In [49]:
#standardize the customer column and find all transactions made by sneha
df["Customer"]=df["Customer"].str.title()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      laptop   55000
1            1002    Priya      mobile   25000
2            1003     Arun      tablet   30000
3            1004    Sneha  headphones    5000
4            1005    Kiran       mouse    1500
5            1006   Anjali    keyboard    2500
6            1007   Vikram     monitor   18000
7            1008    Meena      laptop   55000
8            1009    Rahul      mobile   22000
9            1010    Sneha  headphones    5000
10           1010    Sneha  headphones    5000
11           1011    Kiran       mouse    1500

In [51]:
#before cleaning the data,identify the unique values in the customer and product columns.then standardize both
#columns and check the unique values again

In [63]:
#create a cleaned version of the sales dataframe where
df["Customer"],df["Product"]=df["Customer"].str.strip().str.title(),df["Product"].str.strip().str.title()
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [71]:
#Data Set 2
data = {
   "VisitID": [501, 502, 503, 504, 505,506, 507, 508, 509, 510, 510, 511],
   "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran","Anjali", "Ravi", "Meena", "Arun", "Priya","Priya", "Kiran"],
   "Department": ["Cardiology", "Neurology", "Orthopedic", "General","Dental", "Cardiology", "Neurology", "General","Dental", "Cardiology", "Cardiology", "Dental"],
   "BillAmount": [5000, 7500, 4500, 2000, 1500,6000, 7000, 2500, 1800, 6000,6000, 1500]}
df = pd.DataFrame(data)
print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [74]:
df["Patient"]=df["Patient"].str.strip()
print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500